# Insert your own values in the following fields
PAGE_ACCESS_TOKEN: ""
PAGE_ID: ""
# No need to change these values
IMAGES_DIR: "./src/images"
PDF_DIR: "./src/pdfs"
# IMAGE_QUALITY: 1024, 2048, 4096, etc.
IMAGE_QUALITY: 2048
# Change the PDF_URL to the URL of the PDF you want to use
PDF_URL: ""
# Set the schedule time for each page range, along with the message to be posted.
# dateTime should be in the format "YYYY-MM-DD HH:MM"
SCHEDULE_CONFIG:
  - startPage: 1
    endPage: 5
    message: ""
    dateTime: "2024-12-26 10:00"
  - startPage: 6
    endPage: 10
    message: "Message 2"
    dateTime: "2024-12-27 11:00"
